### ISSUE TITLE
Crypto import error on windows.

### ISSUE THREAD

**Issue by dark-lbp** [cisco-sas/katnip#15]
At windows environment, when i import any model from katnip.model.low_level i will got this error.
```python
Traceback (most recent call last):
  File "C:\tools\test\runner.py", line 9, in <module>
    from katnip.model.low_level.fs_iterators import FsNames
  File "build\bdist.win32\egg\katnip\model\__init__.py", line 2, in <module>
  File "build\bdist.win32\egg\katnip\model\low_level\__init__.py", line 2, in <module>
  File "build\bdist.win32\egg\katnip\model\low_level\encoder.py", line 28, in <module>
ImportError: No module named Crypto.Cipher
```
Because Windows Crypto lib name is 'crypto', it's different than other system.
To fix this problem i have to add this code before import  Crypto.Cipher.
```
import sys
import crypto
sys.modules['Crypto'] = crypto
```

Should i edit the katnip.model.low_level.encoder.py file to 
```python
import sys
if sys.platform.startswith("win32"):
    import crypto
    sys.modules['Crypto'] = crypto
from Crypto.Cipher import AES, DES, DES3
from bitstring import Bits
from kitty.model.low_level.encoder import StrEncoder
from kitty.core import KittyException
```

There might be a better way to fix this problem.

**Comment by dark-lbp** [comment]
I found the reason, because i installed crypto lib before, and it create a 'crypto' folder in my 'site-packages' folder. 
so when i install pycrypto lib, it will install all files to 'crypto' folder, because windows is case-insensitive .
So this is not katnip issues.
